### PR TITLE
Extending Musketeer to newer Ubuntu releases

### PR DESCRIPTION
**Pull request by vpapaioannou**
This PR fixes the issues identified in #1.

### CODE REVIEW

**Comment by ms705** [comment]
Hi @vpapaioannou,

Thanks for this PR!

Two small requests:
1. Please update your git config so that the commits are attributed to your GitHub account (they currently show up as `Papaioannou Vassilis <vpapa@cslab.ece.ntua.gr>`; you can either fix this by adding your cslab email to your GitHub account, or by setting the `user.name` and `user.email` options via the `git config` command (see [here](https://help.github.com/articles/setting-your-username-in-git/))
2. Please squash the commits, since the second one merely corrects a mistake in the first, and the diff becomes clearer when the add/remove of the generated code is eliminated. See [here](https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) for some guidance (basically, `git rebase -i HEAD~2`, followed by setting the "squash" option, then `git push origin master --force`).

@ICGog, can you review this once the above changes have been made?

**Comment by ms705** [comment]
P.S.: Oh, and can you also remove logs.txt from this PR? I don't think we should push the log into the repository, even though it will be useful for debugging your issue.

**Comment by vpapaioannou** [comment]
Hopefully, I think that I fixed all issues regarding the pull request. If there is anything else that should be done, let me know.

**Comment by ms705** [comment]
LGTM :+1: 

@ICGog, can you review as well?

**Comment by ICGog** [comment]
LGTM. Thanks for the pull.

**Pull request merged**
